version: '3.6'
services:
  python:
    restart: always
    build:
      context: .
      dockerfile: ./infra/docker/python/Dockerfile
    container_name: 'book-python-tdd'
    working_dir: '/opt/work/'
    tty: true
    volumes:
      - ./src/:/opt/work
    environment:
      - TZ=Asia/Tokyo
