spring.application.name=learn-spring-boot
logging.level.org.springframework=trace
spring.devtools.remote.restart.enabled=true
spring.devtools.livereload.enabled=true

currency-service.url=http://dev.default.in28minutes.com
currency-service.userName=defaultUsernameDev
currency-service.key=defaultkeyDev