spring.application.name=learn-spring-boot
logging.level.org.springframework=info

currency-service.url=http://default.in28minutes.com
currency-service.userName=defaultUsername
currency-service.key=defaultkey