version: '3.6'
services:
  node:
    restart: always
    build:
      context: .
      dockerfile: ./infra/docker/volta/Dockerfile
    container_name: js
    hostname: js
    working_dir: /opt/work/
    tty: true
    ports:
      - target: 3000
        published: 3000
    volumes:
      - type: bind
        source: ./src
        target: /opt/work
    environment:
      - TZ=Asia/Tokyo

